### ISSUE TITLE
大佬，一个业务时间是多长时间啊 

### ISSUE THREAD

**Issue by tangdoudou18** [ifzc/Shkjem#1]
RT

**Comment by ifzc** [comment]
感谢关注到这个项目，是字打错了已改正，这个外包项目前后端加起来一共3周左右的时间，后面有少许的样式修改

**Comment by tangdoudou18** [comment]
@ifzc 喔喔  吓我一跳。    我一个做一个业务的时间就做完了，这速度也太恐怖啦。这个项目是用jade.  刚刚百度了一下 。就是不知道会不会用 - -

**Comment by ifzc** [comment]
哈哈，是的，这个项目使用Jade是忍着代码可能看起来极为不适的尝试，现在不太推荐使用Jade这种模板，做这个项目的时候Vue也是刚刚上手，对前端比较感兴趣，加上Vue文档齐全

**Comment by tangdoudou18** [comment]
@ifzc 有没有方法或者工具把这个jade代码转成html代码

**Comment by ifzc** [comment]
https://html2jade.org
这个网站可以帮助你互转
