### ISSUE TITLE
为什么感觉很慢呢？

### ISSUE THREAD

**Issue by xmge** [ifzc/Shkjem#14]

**Comment by ifzc** [comment]
测试服务器带宽太低了（1mbp😂），虽在技术层面做了懒加载，稍微加载大点的图还是很拉胯
正式环境带宽高一点，图片大小压缩至正常范围200kb以内的话就不会慢的

![image](https://user-images.githubusercontent.com/30067329/90580569-cd8f8f80-e1fb-11ea-9fec-7eb9b6f6575c.png)
