### ISSUE TITLE
路过.....

### ISSUE THREAD

**Issue by langyuxiansheng** [ifzc/Shkjem#15]
如果是公司自己的官网,vue spa可能不太合适,做外包的话可能是钱没给够.SEO的时候太难了. [捂脸][捂脸]

**Comment by ifzc** [comment]
是的 spa 不利于搜索引擎，SEO 这个项目需求是说没有要求，不过现在可以通过配置去掉 # 号，至少看起来的话要正常一些 😂

**Comment by langyuxiansheng** [comment]
表面是正常的,不是内行的基本上看不出来

**Comment by ifzc** [comment]
没毛病 😄

**Comment by hlj2722** [comment]
可以使用nuxt进行服务端渲染

**Comment by BigData-YC** [comment]
> 如果是公司自己的官网,vue spa可能不太合适,做外包的话可能是钱没给够.SEO的时候太难了. [捂脸][捂脸]

自己的网站，一般都用什么做啊

**Comment by langyuxiansheng** [comment]
> > 如果是公司自己的官网,vue spa可能不太合适,做外包的话可能是钱没给够.SEO的时候太难了. [捂脸][捂脸]
> 
> 自己的网站，一般都用什么做啊

自己的网站,要想上搜索引擎呢  就用SSR渲染技术,ejs,前后端分离的可以用vue   nuxtjs. react nextjs 等.

**Comment by langyuxiansheng** [comment]
> > > 如果是公司自己的官网,vue spa可能不太合适,做外包的话可能是钱没给够.SEO的时候太难了. [捂脸][捂脸]
> > 
> > 
> > 自己的网站，一般都用什么做啊
> 
> 自己的网站,要想上搜索引擎呢 就用SSR渲染技术,ejs,前后端分离的可以用vue nuxtjs. react nextjs 等.

如果是纯静态的纠结
