### ISSUE TITLE
为什么代码运行出来的页面没有像你最终版本那样有动画效果

### ISSUE THREAD

**Issue by linting-g** [ifzc/Shkjem#31]

**Comment by ifzc** [comment]
可以看下是否是因为浏览器兼容性问题，可以用最新的Chrome看下是否能正常，这个站点最低兼容性是IE10，IE11或者以上都不会有问题

**Comment by chaojieChen225** [comment]
我也遇到了同样的问题。。。下载代码下来并发现没有动画效果（滚动的时候没有）

**Comment by KunlunLu** [comment]
代码不是最新的吧，和效果不一样

**Comment by ifzc** [comment]
@KunlunLu 最终版本是 https://github.com/ifzc/Shkjem/releases/tag/v1.0 这个，这里的是改进之后的版本，更加稳定兼容性更好

**Comment by KunlunLu** [comment]
@ifzc 新手小白，多谢大佬
