### ISSUE TITLE
大佬打扰一下 请问后端怎么用呢

### ISSUE THREAD

**Issue by ziyumiao** [ifzc/Shkjem#39]
学习了大佬的前端代码，但是不太会C#，感觉前后端对不上这样

**Comment by ifzc** [comment]
后端要稍微复杂点，我看下要不要把后端也整个Docker，这样的话两行命令就可以在任何地方启动了，但是我后面写的后端接口和现在那个网站上跑的有差异的，正式版本的后端交付出去后，后台账号密码之后甲方有，我重新写的这套后端接口是没有和这个前端页面没有做对接，只当作的练手的后端项目去实践一些后端学到的技术
