### ISSUE TITLE
大佬想问问这个可以手机端适配吗？

### ISSUE THREAD

**Issue by lin1314520** [ifzc/Shkjem#44]
现在好像我把尺寸换成手机的尺寸后，会很多样式走形0.0，有木有啥好办法可以解决适配的问题

**Comment by ifzc** [comment]
- 这个没有做对手机的自适应
- 但是如果想在这个基础上加上手机的自适应，也是可以，只是要去依次调，但是我还是觉得这样有一些僵硬，很容易把PC和H5代码弄的很混乱（如果想学习H5的话，就大胆改造吧，现有的样式还算比较规范，改起来应该不算太费劲）
- 现在好多一线厂商，都是PC和手机分开了，两套页面，PC版本和H5版本，H5版本的需求越来越少了
- 建议需要H5的话分开开发，两套代码（代码阅读体验和开发体验舒服多了），两个域名，打开网页的时候根据设备和尺寸判断选择打开哪个域名
- **这个是个人意见，仅供参考**
