### ISSUE TITLE
正式环境与master分支的代码不一致，大佬能更新一波吗？

### ISSUE THREAD

**Issue by St-coder** [ifzc/Shkjem#47]
![image](https://user-images.githubusercontent.com/16557111/197670948-2c6e371a-b459-4ea8-9ce9-45aa7efe39c8.png)

![image](https://user-images.githubusercontent.com/16557111/197670812-50e54ec7-e6a5-4aa4-8465-dfe4fcfbf2dd.png)

求大佬更新！

**Comment by ifzc** [comment]
master 上的版本是在正式域名版本之上的深度优化版，去掉了这两个标识，同时支持滑动上下翻页，之前这个版本存在很多兼容性问题，学习的话还是建议看 master 它是完整的优化升级版本，域名对应的版本归档在：https://github.com/ifzc/Shkjem/releases/tag/v1.0
