### ISSUE TITLE
大佬想问你这个要怎么部署

### ISSUE THREAD

**Issue by sky-xy** [ifzc/Shkjem#49]
我怎么试了半天没有部署出来 可能我比较小白吧

**Comment by ifzc** [comment]
你使用 docker 部署的，还是直接部署的

**Comment by sky-xy** [comment]
直接部署的

**Comment by sky-xy** [comment]
就你的文档里面那些我有点看不懂...我用的是国内的宝塔面板部署的.有空的话可以教教我嘛

**Comment by ifzc** [comment]
我前面也用过宝塔，宝塔纯界面操作，根目录中放build生成的文件，设置好域名后，就可以访问了，你试试看，网上也有很多静态网站宝塔发布的文章，你build后生成的文件你可以理解为静态网站；
![image](https://user-images.githubusercontent.com/30067329/201634912-ef4d965f-aba0-4da7-859f-c46cbdb10f28.png)
