### ISSUE TITLE
后台登录

### ISSUE THREAD

**Issue by Whze** [ifzc/Shkjem#54]
你好，请问一下有对应后台登录的账号密码吗？没有的话是不是没办法浏览admin模块的界面

**Comment by ifzc** [comment]
这个账号密码交出去之后我也不知道，但是你可以注释掉检验
https://github.com/ifzc/Shkjem/blob/master/src/router.js
此文件最底部校验逻辑
注释之后可以跳过登录直接访问admin页面，因为跳过了登录没有token，所以没权限新增、修改和删除，但是可以查看页面和数据；
