### ISSUE TITLE
请问开源协议什么？

### ISSUE THREAD

**Issue by ztkboj58623** [ifzc/Shkjem#60]
请问开源协议什么？

**Comment by ifzc** [comment]
不是太懂开源协议，所以这个没有开源协议

**Comment by hualing0108** [comment]
请问作者可以在此源码上进行二开 然后发布到公司官网上吗

**Comment by ifzc** [comment]
可以的

**Comment by Xminghaozz** [comment]
作者大佬，这个可以改了自己公司用吗

**Comment by ifzc** [comment]
可以的，我就是把它当作一个模板分享出来学习或者复用的

**Comment by Xminghaozz** [comment]
大佬，前端的发展历程里面的小块在前端能直接改吗
我没有找到呢

**Comment by ifzc** [comment]
发展历程也是存在数据库中调接口取的，之前很多地方的设计是在管理页中配置的，你可以看下那个页面所有调用的接口，前端页面中也有一个对应的循环渲染出来的，如果想直接改可以去掉接口调用，直接写在前端页面中

**Comment by Xminghaozz** [comment]
佬，还有些问题请教你，有偿，能加个V吗，X1095870192

**Comment by Mamong** [comment]
测试账号：admin 123456
这个登录不了http://kejian.filog.cn/#/login?redirect=%2Fadmin

**Comment by ifzc** [comment]
> 测试账号：admin 123456 这个登录不了http://kejian.filog.cn/#/login?redirect=%2Fadmin

1. 这个网站调用的接口是交付出去的版本，只有客户有账号密码，不是测试版，所以肯定是登录不了的😂
2. 想进去的话，可以在vue路由中把限制去掉直接访问里面的页面，但是因为没有登录，没有token，所以也只能查询数据，没有权限做任何修改
3. 想能登录并能做操作的话，可以部署一套数据库+后端api接口（在介绍中有），这样就是完全体了

**Comment by ifzc** [comment]
> 佬，还有些问题请教你，有偿，能加个V吗，X1095870192

请教谈不上，有偿也不必，交流的话都欢迎👀

**Comment by Mamong** [comment]
> > 测试账号：admin 123456 这个登录不了http://kejian.filog.cn/#/login?redirect=%2Fadmin
> 
>     1. 这个网站调用的接口是交付出去的版本，只有客户有账号密码，不是测试版，所以肯定是登录不了的😂
> 
>     2. 想进去的话，可以在vue路由中把限制去掉直接访问里面的页面，但是因为没有登录，没有token，所以也只能查询数据，没有权限做任何修改
> 
>     3. 想能登录并能做操作的话，可以部署一套数据库+后端api接口（在介绍中有），这样就是完全体了

谢谢回复，我以为给了账号是测试版的，但是代码里看又是线上的地址。
