### ISSUE TITLE
安装的时候会报错，是不是库版本

### ISSUE THREAD

**Issue by fkxgood** [ifzc/Shkjem#61]
![image](https://user-images.githubusercontent.com/83326423/227089855-ddf66741-a7bb-4522-aa4d-838230c977e9.png)

**Comment by ifzc** [comment]
不好意思，很久没关注回复晚了，你这个问题我看其他人都没有遇到，可能是因为你在Linux环境中的原因，但是我觉得应该是版本的问题，你可以升级下npm和node试试
