### ISSUE TITLE
请问大佬这个是响应式的么

### ISSUE THREAD

**Issue by zzy199909** [ifzc/Shkjem#63]
我最近也在做自家公司的官网，好高兴看到大佬的这个项目，我最头疼的就是响应式了，但是我看大佬的这个项目好像是没做的，我想请教一下大佬关于响应式有没有啥建议可以给到我的呀

**Comment by ifzc** [comment]
响应式这个看选择，我只能提供下我个人的选择：

- 如果只做PC的响应式，去兼容不同size的屏幕（1080p\2k\4k）这个的响应式我觉得是必要的
- 但是直接开发为响应式的PC和移动端，现在对移动端的设计交互也更加复杂和精致，结构和交互上都会很大变化，这种情况，我就会直接把这个页面开发两个版本PC和移动端，打开页面判断是否时移动端，是就无感跳转到移动端版本，两版代码都是干净的，且互不影响，维护成本很低，开发时间也会减少
- 如果是PC和手机版差距很小的话可以响应式直接去开发，这个你可以开发之前先根据需求评估下
- 而且官网的话没必要去考虑移动端，用手机浏览器的人实在少数中的少数，除非是要在什么微信公众号中展示之类的情况

不过这也是我个人觉得比较合理的做法，不一定对，只能给到你参考
