### ISSUE TITLE
这份前端代码怎么和您仓库里的.net core 参数不匹配

### ISSUE THREAD

**Issue by zyhzyh1383** [ifzc/Shkjem#64]
这份前端代码怎么和您仓库里的.net core 参数不匹配，比如登录LoginInputDto要求LoginName和Password,而前端传的是strUser和strPss,响应格式也不匹配？

**Comment by zyhzyh1383** [comment]
很多方法的请求方式也不匹配，比如get post

**Comment by ifzc** [comment]
后端的代码是.net core的，是升级过的版本，可用但是未对接，为了练练架构升级的；
和正式对接的完全一样的版本我保留了一份在tag/v1，这个版本很老并且不是core的
https://github.com/ifzc/Shkjem/releases/tag/v1.0

**Comment by ifzc** [comment]
新版本路由完全按照restful设计的，更加简洁规范，是有差异，新版本架构相关做了很多封装，包括基础响应对象，异常处理，授权认证，Swagger之类的，且全部抽出来在 [KeJian.Core.Library] ,整个结构也按照DDD的设计的，每个项目比较清晰明了，打磨了很久出的；后面做项目还会沿用这里面的很多东西，做这个比前端要研究的更多，因为我是个后端开发，前端是兴趣使然学的👀
