### ISSUE TITLE
您好，您的node版本是多少呀，我怎么都跑不起来

### ISSUE THREAD

**Issue by niubility6** [ifzc/Shkjem#65]
您好，您的node版本是多少呀，我怎么都跑不起来

**Comment by ifzc** [comment]
因为是用脚手架建的项目，我一直没有太关注node版本，基本上稳定版的node都可以正常运行，你可以看下具体是什么错误？

**Comment by ifzc** [comment]
@niubility6 
我刚刚使用v18.13.0版本的node出错了
![image](https://github.com/ifzc/Shkjem/assets/30067329/f9fb84e6-c19c-418b-8229-8db7d50f4fd8)

按照这个方法解决后就可以了
![image](https://github.com/ifzc/Shkjem/assets/30067329/88608e93-1f7f-415b-bb88-74c203fee31b)

![image](https://github.com/ifzc/Shkjem/assets/30067329/5239c298-de20-4654-bb9c-87c76a400ff7)

可以根据具体错误看如何解决
