### ISSUE TITLE
这个代码是最新的吗

### ISSUE THREAD

**Issue by Pcactus** [ifzc/Shkjem#7]
我下载看了一下，这个代码好像不是最新的啊，有最新的代码可以提供学习一下吗
![image](https://user-images.githubusercontent.com/37173155/74132911-6c6e7a00-4c22-11ea-8787-dfbca2c6203e.png)

**Comment by ifzc** [comment]
现在的这个是优化过的版本，老的版本和线上一致的是这个
这里 ：https://github.com/ifzc/Shkjem/releases
