### ISSUE TITLE
请教作者的项目运行的版本

### ISSUE THREAD

**Issue by waterworld-warehouse** [ifzc/Shkjem#70]
作者您好:
  您的nodejs版本，npm版本，vuecli版本是啥？
  请教一下，本地npm install安装一直失败，猜测可能是因为版本不同导致的（我本机的nodejs是16.20.1，npm是8.19.4）。

**Comment by ifzc** [comment]
有具体的错误吗，我本机v18.13.0，V16应该也不会有问题的，这里面用的包不算多

**Comment by ifzc** [comment]
基本上拿着报错，给GPT就可以解决，你试下

**Comment by waterworld-warehouse** [comment]
这么神奇。那我说下我的安装流程哈。首先npm install时，终端提示淘宝镜像过期了，我将项目里面全部的https://registry.npm.taobao.org/改成了https://registry.npmmirror.com。然后就npm install成功了。

然后执行npm run serve。报错说TypeError: transpileDependencies.map is not a function
截图如下：
[
![报错的原因](https://github.com/ifzc/Shkjem/assets/65522098/b2982caf-6142-4c3a-92e2-b65f2a792b50)
](url)



然后gpt说这个错误通常是由于npm版本不兼容导致的。在旧版本的npm中，transpileDependencies是一个字符串数组，我们可以直接配置需要编译的依赖库。而在较新版本的npm中，transpileDependencies被改成了一个对象，并且需要使用map()方法来处理。因此，如果我们在较新版本的npm中使用了旧版本的配置方式，就会导致transpileDependencies.map不是一个函数的错误。
TypeError: transpileDependencies.map is not a function
修改 vue.config.js，添加配置项 transpileDependencies: [] ，就可以了
难搞，找不到vue.config.js文件，所以来请教一下作者

**Comment by ifzc** [comment]
![image](https://github.com/ifzc/Shkjem/assets/30067329/75ff2404-6e1e-41f5-b023-8d2baa84c4db)
![image](https://github.com/ifzc/Shkjem/assets/30067329/c5a46a10-3004-4779-bd4a-bdc289c29410)
![image](https://github.com/ifzc/Shkjem/assets/30067329/3b5d103d-8f4a-4348-8ca0-eec524e6d21f)

我刚又试了下，还是可以的，这是我的版本，你是在没有任何代码改动的情况下还原的吗，尤其是npm没有自动改你包的版本吧，原本是没有这个vue.config.js文件的

**Comment by waterworld-warehouse** [comment]
作者您好，我是安装了你那个分支的[dependabot/npm_and_yarn/multi-5eb6fd4436]，不是主干的哈(https://github.com/ifzc/Shkjem/tree/dependabot/npm_and_yarn/multi-5eb6fd4436)

然后就只改了那个package-lock.json和dockerfile的淘宝镜像地址。

要不作者你试试npm install你那个分支之后，然后再试试启动一下

**Comment by ifzc** [comment]
不要不试下直接拉取master，不做修改，先成功后，在做修改
