### ISSUE TITLE
HI 兄弟  你的特效版是哪个分支啊

### ISSUE THREAD

**Issue by wangsir92** [ifzc/Shkjem#71]
HI 兄弟  你的特效版是哪个分支啊？

**Comment by ifzc** [comment]
官网上完全一样的特效是：https://github.com/ifzc/Shkjem/releases/tag/v1.0

**Comment by xiaoming-king** [comment]
您好，可以直接拿来使用吗？

**Comment by ifzc** [comment]
> 您好，可以直接拿来使用吗？

可以的
