### ISSUE TITLE
请教一下，这个手机或平板端有自适应界面吗

### ISSUE THREAD

**Issue by waterworld-warehouse** [ifzc/Shkjem#74]
前端有没有在不同设备自适应，请教一下

**Comment by beckapi** [comment]
没有，我个人还是喜欢分两个版本，手机和PC，判断然后跳对应版本页面

**Comment by ifzc** [comment]
现在PC和手机版页面差异太大了，我个人不太喜欢做自适应，喜欢分两个版本的页面，代码两边都干净，进入的时候跳转到对应版本

**Comment by waterworld-warehouse** [comment]
有另外一个版本的科建吗

**Comment by waterworld-warehouse** [comment]
假如说你有两个版本的代码

**Comment by ifzc** [comment]
没有，这个网站做的时候没有移动端的需求

**Comment by waterworld-warehouse** [comment]
> 没有，这个网站做的时候没有移动端的需求

技术高超的up主，有没有哪些地方能找到这些能自适应的官网代码，请教一下，想做一个官网

**Comment by ifzc** [comment]
问了下 ChatGpt 4 第一个项目看起来很适合：

> 推荐几个GitHub中的优秀H5自适应网站项目，中文回答?

这里有几个GitHub上的优秀H5自适应网站项目推荐：

1. h5-vue3-vite-vuecli5 - 这个项目是一个企业级的H5自适应工程模板，使用了TypeScript, Vue3, Vite, Webpack5, 和viewport等技术。它集成了ESLint, Stylelint, Prettier, 和Husky等工程化工具来提高代码质量和开发效率​ ([GitHub](https://github.com/JuneHello/h5-vue3-vite-vuecli5))​。

2. Responsive-Web-Design - 这个项目提供了一个响应式网页设计解决方案，特别关注于PC端和移动端的自适应。它利用CSS的媒体查询和百分比宽度来实现不同设备上的自适应显示​ ([GitHub](https://github.com/haoxihuanzise/Responsive-Web-Design))​。

3. adaptive - 该项目提供了一个移动端H5页面自适应框架，简单易用。它允许开发者通过简单的JavaScript脚本来调整HTML元素的字体大小和布局，使得设计图的像素与设备显示像素能够精确匹配​ ([GitHub](https://github.com/wangmeng93/adaptive))​。

这些项目各有特点，可以根据你的具体需求选择合适的一个进行深入了解和使用。每个项目的GitHub页面都有详细的使用说明和代码，你可以查看具体的实现方式和示例代码。

**Comment by waterworld-warehouse** [comment]
> 问了下 ChatGpt 4 第一个项目看起来很适合：
> 
> > 推荐几个GitHub中的优秀H5自适应网站项目，中文回答?
> 
> 这里有几个GitHub上的优秀H5自适应网站项目推荐：
> 
> 1. h5-vue3-vite-vuecli5 - 这个项目是一个企业级的H5自适应工程模板，使用了TypeScript, Vue3, Vite, Webpack5, 和viewport等技术。它集成了ESLint, Stylelint, Prettier, 和Husky等工程化工具来提高代码质量和开发效率​ ([GitHub](https://github.com/JuneHello/h5-vue3-vite-vuecli5))​。
> 2. Responsive-Web-Design - 这个项目提供了一个响应式网页设计解决方案，特别关注于PC端和移动端的自适应。它利用CSS的媒体查询和百分比宽度来实现不同设备上的自适应显示​ ([GitHub](https://github.com/haoxihuanzise/Responsive-Web-Design))​。
> 3. adaptive - 该项目提供了一个移动端H5页面自适应框架，简单易用。它允许开发者通过简单的JavaScript脚本来调整HTML元素的字体大小和布局，使得设计图的像素与设备显示像素能够精确匹配​ ([GitHub](https://github.com/wangmeng93/adaptive))​。
> 
> 这些项目各有特点，可以根据你的具体需求选择合适的一个进行深入了解和使用。每个项目的GitHub页面都有详细的使用说明和代码，你可以查看具体的实现方式和示例代码。

牛啊，谢谢技艺高超的UP主，我这就去看看。
