### ISSUE TITLE
求一份最新代码学习

### ISSUE THREAD

**Issue by NLRX-WJC** [ifzc/Shkjem#8]
作者大佬你好，项目里的代码clone下来跑起来之后的效果跟 http://www.shkjem.com 这个里面的不一样呢，能否求一份 这个网站 http://www.shkjem.com 的前端源码学习学习，谢谢大佬了

**Comment by ifzc** [comment]
现在版本是优化过的版本（最新），和 http://www.shkjem.com 一致的版本在 pak 中

**Comment by ifzc** [comment]
这里 ：https://github.com/ifzc/Shkjem/releases
